In [59]:
require(dplyr)

In [13]:
data <- read.csv("master_data.csv")

In [14]:
glimpse(data)

Rows: 550
Columns: 8
$ UNIQUE_ID         <chr> "GSK01", "GSK02", "GSK03", "GSK04", "GSK05", "GSK06"~
$ PRODUCT_NAME      <chr> "A Masks", "N hand sanitizer,350 ml", "G Channa Dal,~
$ COMPANY           <chr> "A", "N", "G", "I", "S", "S", "S", "G", "Z", "A", "Z~
$ PRODUCT_TYPE      <chr> "hygiene", "hygiene", "foodgrains&spices", "Organic ~
$ PRODUCT_CATEGORY  <chr> "mask", "sanitizer", "pulses(dal)", "Dry Fruits", "b~
$ COST_PRICE        <dbl> 160.00, 248.00, 162.00, 77.14, 494.50, 445.05, 270.0~
$ SELLING_PRICE     <dbl> 200.000, 400.000, 180.000, 133.000, 593.400, 534.060~
$ QUANTITY_DEMANDED <int> 890, 800, 456, 100, 111, 111, 360, 52, 27, 353, 500,~

### Problem Statement

* We are provided a csv dataset for a department store. It contans details of products from May 2020, a period in which COVID-19 heavily impacted sales. 

* We describe trends, analyze patterns and explore data to inform strategic decision making.

#### Adding profit, profit%, net profit, and saving the dataset

In [15]:
data1 <- mutate(data, PROFIT = SELLING_PRICE-COST_PRICE)

In [16]:
data2 <- mutate(data1, PROFIT_PERCENT = PROFIT/COST_PRICE * 100)

In [17]:
data3 <- mutate(data2, NET_PROFIT = PROFIT*QUANTITY_DEMANDED)

#### Saving the data in an updated file

In [55]:
write.table(data3, file = "master_data2.csv", sep =",")

##### Ordering by Profit Margin descending, lets look in the first 20 rows for information on companys A, I, and S.

In [53]:
data_view <- data3
data_view %>%  select(c(0:11)) %>% slice(1:20) %>% filter(COMPANY %in% c("A","I","S")) %>%  arrange(desc(PROFIT_PERCENT))

  UNIQUE_ID PRODUCT_NAME                        COMPANY PRODUCT_TYPE
1 GSK04     I Organic Raisins,100g              I       Organic food
2 GSK10     A mosquitto repellent               A       household
3 GSK19     A mosquitto coil                    A       household
4 GSK01     A Masks                             A       hygiene
5 GSK05     S Body oil                          S       beauty products
6 GSK15     A Body oil                          A       beauty products
7 GSK06     S AloeverS Gel                      S       beauty products
8 GSK12     I chocolate flavour Cornflakes, 1kg I       Packed Food
9 GSK07     S edible oil,1L                     S       foodgrains&spices
  PRODUCT_CATEGORY COST_PRICE SELLING_PRICE QUANTITY_DEMANDED PROFIT
1 Dry Fruits        77.14     133.000       100                55.860
2 repellents       171.00     225.000       353                54.000
3 repellents        95.00     125.000       353                30.000
4 mask             160.00     200.000       890                40.000
5 bodycare         494.50     593.400       111                98.900
6 bodycare         516.26     619.512       119               103.252
7 bodycare         445.05     534.060       111                89.010
8 Dry Fruits       515.00     592.250       188                77.250
9 edible oil       270.00     300.000       360                30.000
  PROFIT_PERCENT NET_PROFIT
1 72.41379        5586.00
2 31.57895       19062.00
3 31.57895       10590.00
4 25.00000       35600.00
5 20.00000       10977.90
6 20.00000       12286.99
7 20.00000        9880.11
8 15.00000       14523.00
9 11.11111       10800.00

#### Statistical Interpretation

When operating a business we ask the following questions 

* What products to produce?
* For who do we produce? Do target customers have high or low purchasing power?
* How should we produce the product?

#### Gathering descriptive statstics for each product type

In [81]:
data3 <- group_by(data3, PRODUCT_TYPE)

In [87]:
glimpse(data3)

Rows: 550
Columns: 11
Groups: PRODUCT_TYPE [12]
$ UNIQUE_ID         <chr> "GSK01", "GSK02", "GSK03", "GSK04", "GSK05", "GSK06"~
$ PRODUCT_NAME      <chr> "A Masks", "N hand sanitizer,350 ml", "G Channa Dal,~
$ COMPANY           <chr> "A", "N", "G", "I", "S", "S", "S", "G", "Z", "A", "Z~
$ PRODUCT_TYPE      <chr> "hygiene", "hygiene", "foodgrains&spices", "Organic ~
$ PRODUCT_CATEGORY  <chr> "mask", "sanitizer", "pulses(dal)", "Dry Fruits", "b~
$ COST_PRICE        <dbl> 160.00, 248.00, 162.00, 77.14, 494.50, 445.05, 270.0~
$ SELLING_PRICE     <dbl> 200.000, 400.000, 180.000, 133.000, 593.400, 534.060~
$ QUANTITY_DEMANDED <int> 890, 800, 456, 100, 111, 111, 360, 52, 27, 353, 500,~
$ PROFIT            <dbl> 40.000, 152.000, 18.000, 55.860, 98.900, 89.010, 30.~
$ PROFIT_PERCENT    <dbl> 25.00000, 61.29032, 11.11111, 72.41379, 20.00000, 20~
$ NET_PROFIT        <dbl> 35600.00, 121600.00, 8208.00, 5586.00, 10977.90, 988~

In [79]:
summarise(data3, AVG=mean(NET_PROFIT))

   PRODUCT_TYPE      AVG
1  baby product      27383.333
2  beauty products    8951.721
3  beverage          10186.731
4  dairy products     9820.000
5  foodgrains&spices  7347.682
6  household         17889.657
7  hygiene           39050.598
8  Organic food       6003.067
9  Packed Food       11891.275
10 pet food          10095.667
11 snacks             6063.144
12 Spreads&Sauces    15856.172

In [80]:
summarise(data3, AVG=mean(NET_PROFIT))

   PRODUCT_TYPE      AVG
1  baby product      27383.333
2  beauty products    8951.721
3  beverage          10186.731
4  dairy products     9820.000
5  foodgrains&spices  7347.682
6  household         17889.657
7  hygiene           39050.598
8  Organic food       6003.067
9  Packed Food       11891.275
10 pet food          10095.667
11 snacks             6063.144
12 Spreads&Sauces    15856.172

In [89]:
summarise(data3, SUM=sum(NET_PROFIT))

   PRODUCT_TYPE      SUM
1  baby product       164300.0
2  beauty products    895172.1
3  beverage           213921.4
4  dairy products      78560.0
5  foodgrains&spices  668639.0
6  household          375682.8
7  hygiene           2108732.3
8  Organic food       492251.5
9  Packed Food        998867.1
10 pet food            60574.0
11 snacks             388041.2
12 Spreads&Sauces     206130.2

In [90]:
summarise(data3, MINIMUM=min(NET_PROFIT), MAXIMUM=max(NET_PROFIT))

   PRODUCT_TYPE      MINIMUM  MAXIMUM
1  baby product      12520.00  40200.00
2  beauty products    1152.40  16925.49
3  beverage           2880.00  19706.40
4  dairy products     5200.00  14440.00
5  foodgrains&spices   250.80  30600.00
6  household          6426.00  29652.00
7  hygiene            3300.00 136800.00
8  Organic food        223.44  48769.60
9  Packed Food        3408.00  29232.00
10 pet food          10000.00  10314.00
11 snacks              592.00  11248.00
12 Spreads&Sauces    13106.88  19200.00

In [92]:
summarise(data3, MEDIAN = median(NET_PROFIT))

   PRODUCT_TYPE      MEDIAN
1  baby product      28400.000
2  beauty products    9130.688
3  beverage           6958.080
4  dairy products     9610.000
5  foodgrains&spices  6820.400
6  household         19320.000
7  hygiene           28839.360
8  Organic food       3727.920
9  Packed Food       12312.000
10 pet food          10000.000
11 snacks             4520.000
12 Spreads&Sauces    15606.000

In [91]:
summarise(data3, VARIANCE=var(NET_PROFIT))

   PRODUCT_TYPE      VARIANCE
1  baby product      1.081274e+08
2  beauty products   1.505579e+07
3  beverage          3.389832e+07
4  dairy products    9.337800e+06
5  foodgrains&spices 3.111343e+07
6  household         3.358081e+07
7  hygiene           1.213862e+09
8  Organic food      5.063794e+07
9  Packed Food       1.562046e+07
10 pet food          2.225667e+04
11 snacks            1.690445e+07
12 Spreads&Sauces    4.270949e+06

In [93]:
summarise(data3, STANDARD_DEVIATION=sd(NET_PROFIT))

   PRODUCT_TYPE      STANDARD_DEVIATION
1  baby product      10398.4339
2  beauty products    3880.1792
3  beverage           5822.2263
4  dairy products     3055.7814
5  foodgrains&spices  5577.9416
6  household          5794.8949
7  hygiene           34840.5263
8  Organic food       7116.0339
9  Packed Food        3952.2729
10 pet food            149.1867
11 snacks             4111.5017
12 Spreads&Sauces     2066.6275

In [ ]:
summarise(data3, QUANTILE=quantile(NET_PROFIT))

`summarise()` has grouped output by 'PRODUCT_TYPE'. You can override using the
`.groups` argument.

   PRODUCT_TYPE      QUANTILE
1  baby product       12520.000
2  baby product       20785.000
3  baby product       28400.000
4  baby product       34500.000
5  baby product       40200.000
6  beauty products     1152.400
7  beauty products     8526.400
8  beauty products     9130.688
9  beauty products    11352.000
10 beauty products    16925.488
11 beverage            2880.000
12 beverage            6696.000
13 beverage            6958.080
14 beverage           18000.000
15 beverage           19706.400
16 dairy products      5200.000
17 dairy products      8152.500
18 dairy products      9610.000
19 dairy products     11407.500
20 dairy products     14440.000
21 foodgrains&spices    250.800
22 foodgrains&spices   3808.000
23 foodgrains&spices   6820.400
24 foodgrains&spices   9264.830
25 foodgrains&spices  30600.000
26 household           6426.000
27 household          14364.000
28 household          19320.000
29 household          19851.600
30 household          29652.000
31 hygiene             3300.000
32 hygiene            19159.740
33 hygiene            28839.360
34 hygiene            38900.000
35 hygiene           136800.000
36 Organic food         223.440
37 Organic food        1846.320
38 Organic food        3727.920
39 Organic food        6615.000
40 Organic food       48769.600
41 Packed Food         3408.000
42 Packed Food         9672.000
43 Packed Food        12312.000
44 Packed Food        14296.425
45 Packed Food        29232.000
46 pet food           10000.000
47 pet food           10000.000
48 pet food           10000.000
49 pet food           10195.000
50 pet food           10314.000
51 snacks               592.000
52 snacks              2272.000
53 snacks              4520.000
54 snacks             10800.000
55 snacks             11248.000
56 Spreads&Sauces     13106.880
57 Spreads&Sauces     14279.040
58 Spreads&Sauces     15606.000
59 Spreads&Sauces     15698.400
60 Spreads&Sauces     19200.000

In [96]:
summarise(data3, RANGE=range(NET_PROFIT))

`summarise()` has grouped output by 'PRODUCT_TYPE'. You can override using the
`.groups` argument.

   PRODUCT_TYPE      RANGE
1  baby product       12520.00
2  baby product       40200.00
3  beauty products     1152.40
4  beauty products    16925.49
5  beverage            2880.00
6  beverage           19706.40
7  dairy products      5200.00
8  dairy products     14440.00
9  foodgrains&spices    250.80
10 foodgrains&spices  30600.00
11 household           6426.00
12 household          29652.00
13 hygiene             3300.00
14 hygiene           136800.00
15 Organic food         223.44
16 Organic food       48769.60
17 Packed Food         3408.00
18 Packed Food        29232.00
19 pet food           10000.00
20 pet food           10314.00
21 snacks               592.00
22 snacks             11248.00
23 Spreads&Sauces     13106.88
24 Spreads&Sauces     19200.00

#### Filtering on household products, sorted by quantity_demanded

In [113]:
data3 %>% select(c(4:10)) %>% filter(PRODUCT_TYPE == 'household') %>% arrange(QUANTITY_DEMANDED)

   PRODUCT_TYPE PRODUCT_CATEGORY COST_PRICE SELLING_PRICE QUANTITY_DEMANDED
1  household    detergent        649.80     855            70
2  household    detergent        598.88     788            80
3  household    dishwasher       399.00     525           153
4  household    detergent        490.20     645           180
5  household    detergent        329.08     433           200
6  household    dishwasher       277.40     365           223
7  household    freshners        266.00     350           230
8  household    freshners        272.08     358           231
9  household    freshners        269.80     355           233
10 household    repellents       218.88     288           311
11 household    repellents       218.88     288           311
12 household    repellents       142.88     188           311
13 household    repellents       117.80     155           333
14 household    repellents       180.12     237           342
15 household    repellents       180.12     237           342
16 household    detergent        268.28     353           350
17 household    repellents       171.00     225           353
18 household    repellents        95.00     125           353
19 household    repellents       171.00     225           353
20 household    dishwasher        49.40      65           423
21 household    dishwasher        47.88      63           425
   PROFIT PROFIT_PERCENT
1  205.20 31.57895
2  189.12 31.57895
3  126.00 31.57895
4  154.80 31.57895
5  103.92 31.57895
6   87.60 31.57895
7   84.00 31.57895
8   85.92 31.57895
9   85.20 31.57895
10  69.12 31.57895
11  69.12 31.57895
12  45.12 31.57895
13  37.20 31.57895
14  56.88 31.57895
15  56.88 31.57895
16  84.72 31.57895
17  54.00 31.57895
18  30.00 31.57895
19  54.00 31.57895
20  15.60 31.57895
21  15.12 31.57895

In [114]:
require(ggplot2)

Loading required package: ggplot2